using VideoRentalSystem.Commands.Contracts;
using VideoRentalSystem.Data.Contracts;
using System.Collections.Generic;

namespace VideoRentalSystem.Commands.PdfPrintCommands
{
    // <auto-generated/>
    public class ListAllGenresToPdfCommand : ICommand
    {
        private readonly string fileName = @"..\..\..\GenresList.pdf";
        private readonly string imgPath = @"..\..\..\PaperAirplane.jpg";
        private readonly string title = "Genres Report";
        private readonly string header = "Genres Report";
        private readonly string target = "Genres";
        private readonly string author = "Triple Bounty";
        private readonly string keyword = "video rental system";
        private readonly string headerRental = "video rental";
        private readonly string listName = "GENRES LIST\n\n";
        private readonly string subTitle = "What Genres do we have ?";
        private readonly string warningMessage = "All genres can be dropped with a two weeks prior notice. Especially Lamer once.";

        private readonly IDatabase db;

        public ListAllGenresToPdfCommand(IDatabase db)
        {
            this.db = db;
        }

        public string Execute(IList<string> parameters)
        {
            var objectsList = this.db.FilmGenres.GetAll();
            List<string> data = new List<string>();

            if (objectsList.Count == 0)
            {
                data.Add("No items");
            }

            foreach (var item in objectsList)
            {
                data.Add(item.ToString());
            }

            CreatePDF pdfCreator = new CreatePDF(
                                               this.fileName,
                                               this.imgPath,
                                               this.title,
                                               this.header,
                                               this.target,
                                               this.author,
                                               this.keyword,
                                               this.headerRental,
                                               this.listName,
                                               this.subTitle,
                                               this.warningMessage);

            pdfCreator.CreatePdf(data);

            return $"Pdf - {fileName} - with the list of all {target} was created in the project folder";
        }
    }
}