// <auto-generated />
using iTextSharp.text;
using VideoRentalSystem.Commands.Contracts;
using VideoRentalSystem.Data.Contracts;
using System;
using System.Collections.Generic;

namespace VideoRentalSystem.Commands.PdfPrintCommands
{
    // <auto-generated/>
    public class ListAllGenresToPdfCommand : ICommand
    {
        private readonly string fileName = @"..\..\..\GenresList.pdf";
        private readonly string imgPath = @"..\..\..\PaperAirplane.jpg";
        private readonly string title = "Genres Report";
        private readonly string header = "Genres Report";
        private readonly string target = "Genres";
        private readonly string author = "Triple Bounty";
        private readonly string keyword = "video rental system";
        private readonly string headerRental = "video rental";
        private readonly string listName = "GENRES LIST\n\n";
        private readonly string subTitle = "What Genres do we have ?";
        private readonly string warningMessage = "All genres can be dropped with a two weeks prior notice. Especially Lamer once.";

        private readonly IDatabase db;
        private readonly CreatePDF pdf;

        public ListAllGenresToPdfCommand(IDatabase db, CreatePDF pdf)
        {
            this.db = db;
            this.pdf = pdf;
        }

        public void AllObjectsToStringList(List<string> data)
        {
            var objectsList = this.db.FilmGenres.GetAll();
            if (objectsList.Count == 0)
            {
                data.Add("No items");
            }

            foreach (var item in objectsList)
            {
                data.Add(item.ToString());
            }
        }

        public string Execute(IList<string> parameters)
        {
            List<string> data = new List<string>();
            this.AllObjectsToStringList(data);

            this.pdf.CreatePdf(
                this.fileName,
                this.imgPath,
                this.title,
                this.header,
                this.target,
                this.author,
                this.keyword,
                this.headerRental,
                this.listName,
                this.subTitle,
                this.warningMessage,
                data);

            return $"Pdf - {fileName} - with the list of all {target} was created in the project folder";
        }
    }
}