// <auto-generated />
namespace VideoRentalSystem.Migrations.VideoRentalLoanContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class customer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customer));
        
        string IMigrationMetadata.Id
        {
            get { return "201706071320490_customer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
