// <auto-generated />
namespace VideoRentalSystem.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addfilmstaffconstraints : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.FilmStaffs", "FirstName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.FilmStaffs", "LastName", c => c.String(nullable: false, maxLength: 50));
        }
        
        public override void Down()
        {
            AlterColumn("dbo.FilmStaffs", "LastName", c => c.String());
            AlterColumn("dbo.FilmStaffs", "FirstName", c => c.String());
        }
    }
}
