// <auto-generated />
namespace VideoRentalSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mergingwithmydb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mergingwithmydb));
        
        string IMigrationMetadata.Id
        {
            get { return "201706052036480_merging with my db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
