// <auto-generated />
namespace VideoRentalSystem.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addstorage : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.StoreFilms", "Store_Id", "dbo.Stores");
            DropForeignKey("dbo.StoreFilms", "Film_Id", "dbo.Films");
            DropIndex("dbo.StoreFilms", new[] { "Store_Id" });
            DropIndex("dbo.StoreFilms", new[] { "Film_Id" });
            CreateTable(
                "dbo.Storages",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Quantity = c.Int(nullable: false),
                        VideoFormat = c.Int(nullable: false),
                        Film_Id = c.Int(),
                        Store_Id = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Films", t => t.Film_Id)
                .ForeignKey("dbo.Stores", t => t.Store_Id)
                .Index(t => t.Film_Id)
                .Index(t => t.Store_Id);
            
            DropTable("dbo.StoreFilms");
        }
        
        public override void Down()
        {
            CreateTable(
                "dbo.StoreFilms",
                c => new
                    {
                        Store_Id = c.Int(nullable: false),
                        Film_Id = c.Int(nullable: false),
                    })
                .PrimaryKey(t => new { t.Store_Id, t.Film_Id });
            
            DropForeignKey("dbo.Storages", "Store_Id", "dbo.Stores");
            DropForeignKey("dbo.Storages", "Film_Id", "dbo.Films");
            DropIndex("dbo.Storages", new[] { "Store_Id" });
            DropIndex("dbo.Storages", new[] { "Film_Id" });
            DropTable("dbo.Storages");
            CreateIndex("dbo.StoreFilms", "Film_Id");
            CreateIndex("dbo.StoreFilms", "Store_Id");
            AddForeignKey("dbo.StoreFilms", "Film_Id", "dbo.Films", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StoreFilms", "Store_Id", "dbo.Stores", "Id", cascadeDelete: true);
        }
    }
}
