// <auto-generated />
namespace VideoRentalSystem.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class mergingwithmydb : DbMigration
    {
        public override void Up()
        {
            
        }
        
        public override void Down()
        {
            AddColumn("dbo.Addresses", "Country_Id", c => c.Int());
            DropIndex("dbo.Countries", "IX_UniqueCode");
            DropIndex("dbo.Countries", "IX_UniqueName");
            AlterColumn("dbo.Stores", "Name", c => c.String());
            AlterColumn("dbo.FilmStaffs", "LastName", c => c.String());
            AlterColumn("dbo.FilmStaffs", "FirstName", c => c.String());
            CreateIndex("dbo.Addresses", "Country_Id");
            AddForeignKey("dbo.Addresses", "Country_Id", "dbo.Countries", "Id");
        }
    }
}
