// <auto-generated />
namespace VideoRentalSystem.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class removecountryfromaddress : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Addresses", "Country_Id", "dbo.Countries");
            DropIndex("dbo.Addresses", new[] { "Country_Id" });
            DropColumn("dbo.Addresses", "Country_Id");
        }

        public override void Down()
        {
            AddColumn("dbo.Addresses", "Country_Id", c => c.Int());
            CreateIndex("dbo.Addresses", "Country_Id");
            AddForeignKey("dbo.Addresses", "Country_Id", "dbo.Countries", "Id");
        }
    }
}
