// <auto-generated />
namespace VideoRentalSystem.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addaddressconstraints : DbMigration
    {
        public override void Up()
        {
            CreateIndex("dbo.Countries", "Name", unique: true, name: "IX_UniqueName");
            CreateIndex("dbo.Countries", "Code", unique: true, name: "IX_UniqueCode");
        }
        
        public override void Down()
        {
            DropIndex("dbo.Countries", "IX_UniqueCode");
            DropIndex("dbo.Countries", "IX_UniqueName");
        }
    }
}
