// <auto-generated />
namespace VideoRentalSystem.Migrations.VideoRentalContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsDeletedFiledaddedtogenreagerating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsDeletedFiledaddedtogenreagerating));
        
        string IMigrationMetadata.Id
        {
            get { return "201706080820242_IsDeleted Filed added to genre,age rating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
